---
- name: Configure Frontend with NGINX
  hosts: frontend
  become: yes
  tasks:

    - name: Check RAM
      shell: "free -m | awk '/^Mem:/{print $2}'"
      register: ram
      failed_when: ram.stdout | int < 1024
      changed_when: false

    - name: Install NGINX (Debian/Ubuntu only)
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'
      notify: restart nginx

    - name: Install common tools
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - vim
        - curl
        - git

    - name: Deploy HTML file
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Welcome to the Frontend Node</h1>"
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
